workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run: sudo apt update
      - run: sudo LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php
      - run: sudo apt-get update
      - run: sudo apt install curl php-cli php-mbstring php-pgsql php-zip php-xml php-mbstring git unzip
      - run: which php; php -v
      - run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');";
          sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer;
          php -r "unlink('composer-setup.php');"
      - run: cd /home/circleci/project
      - run: composer install
      - run: cd /home/circleci
      - run: sudo rm -rf /home/circleci/.composer
      - run: composer global require laravel/installer
      - run: |
            export PATH="$PATH:$HOME/.config/composer/vendor/bin";
            cd /home/circleci;
            /home/circleci/project/dokku-laravel new project1 project1;
            cd project1
      - run: cd /home/circleci/project1 && docker-compose up -d
      - run: |
            (cd /home/circleci/project1 && php artisan serve ) &
            sleep 20;
            curl -s 127.0.0.1:8000;
            (curl -s 127.0.0.1:8000 | grep Laravel) || false;
      - run: |
            cd /home/circleci/project1 && php artisan migrate;
            (cd /home/circleci/project1 && php artisan serve ) &
            sleep 5;
            echo '<?php echo App\User::count(); ?> users' > /home/circleci/project1/resources/views/welcome.blade.php;
            curl -s 127.0.0.1:8000;
            (curl -s 127.0.0.1:8000 | grep '0 users') || false;
